In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#defining feature names
index_names = ['unit_number', 'time_cycles']
setting_names = ['setting_1', 'setting_2', 'setting_3']
sensor_names = ['s_{}'.format(i+1) for i in range(0,21)]
col_names = index_names + setting_names + sensor_names

In [3]:
train = pd.read_csv('../backend/CMAPSSData/train_FD001.txt',sep='\s+',header=None,index_col=False,names=col_names)
test = pd.read_csv('../backend/CMAPSSData/test_FD001.txt',sep='\s+',header=None,index_col=False,names=col_names)
rul = pd.read_csv('../backend/CMAPSSDATA/RUL_FD001.txt',sep='\s+',header=None,index_col=False,names=['RUL'])

In [6]:
train.describe()

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,2.063100e+04,20631.000000,20631.000000,20631.000000,2.063100e+04,...,20631.000000,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,100.0,5.186700e+02,642.680934,1590.523119,1408.933782,1.462000e+01,...,521.413470,2388.096152,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705
std,29.227633,68.880990,0.002187,0.000293,0.0,6.537152e-11,0.500053,6.131150,9.000605,3.394700e-12,...,0.737553,0.071919,19.076176,0.037505,1.556432e-14,1.548763,0.0,0.0,0.180746,0.108251
min,1.000000,1.000000,-0.008700,-0.000600,100.0,5.186700e+02,641.210000,1571.040000,1382.250000,1.462000e+01,...,518.690000,2387.880000,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,5.186700e+02,642.325000,1586.260000,1402.360000,1.462000e+01,...,520.960000,2388.040000,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800
50%,52.000000,104.000000,0.000000,0.000000,100.0,5.186700e+02,642.640000,1590.100000,1408.040000,1.462000e+01,...,521.480000,2388.090000,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900
75%,77.000000,156.000000,0.001500,0.000300,100.0,5.186700e+02,643.000000,1594.380000,1414.555000,1.462000e+01,...,521.950000,2388.140000,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800
max,100.000000,362.000000,0.008700,0.000600,100.0,5.186700e+02,644.530000,1616.910000,1441.490000,1.462000e+01,...,523.380000,2388.560000,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [11]:
x = scaler.fit_transform(train)

In [13]:
dfx = pd.DataFrame(data=x, columns = train.columns)

In [14]:
dfx.describe()

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21
count,20631.000000,2.063100e+04,2.063100e+04,2.063100e+04,20631.0,20631.0,2.063100e+04,2.063100e+04,2.063100e+04,2.063100e+04,...,2.063100e+04,2.063100e+04,2.063100e+04,2.063100e+04,2.063100e+04,2.063100e+04,20631.0,20631.0,2.063100e+04,2.063100e+04
mean,0.000000,-8.816778e-17,1.377622e-18,-2.720802e-17,0.0,0.0,6.410348e-14,-4.959437e-14,9.285169e-16,-1.776357e-15,...,-1.199702e-13,3.493855e-13,3.061075e-15,-3.244023e-14,-1.387779e-17,1.666922e-14,0.0,0.0,4.156146e-14,2.402296e-14
std,1.000024,1.000024e+00,1.000024e+00,1.000024e+00,0.0,0.0,1.000024e+00,1.000024e+00,1.000024e+00,0.000000e+00,...,1.000024e+00,1.000024e+00,1.000024e+00,1.000024e+00,0.000000e+00,1.000024e+00,0.0,0.0,1.000024e+00,1.000024e+00
min,-1.728084,-1.565170e+00,-3.973523e+00,-2.055419e+00,0.0,0.0,-2.941625e+00,-3.177804e+00,-2.964737e+00,-1.776357e-15,...,-3.692663e+00,-3.005574e+00,-2.296780e+00,-3.126205e+00,-1.387779e-17,-3.364479e+00,0.0,0.0,-3.741634e+00,-3.653688e+00
25%,-0.872708,-8.247448e-01,-6.817340e-01,-6.904875e-01,0.0,0.0,-7.118085e-01,-6.953381e-01,-7.303888e-01,-1.776357e-15,...,-6.148450e-01,-7.807925e-01,-5.508429e-01,-7.264689e-01,-1.387779e-17,-7.817098e-01,0.0,0.0,-6.432961e-01,-6.273114e-01
50%,0.016883,-6.980124e-02,4.055368e-03,-8.021809e-03,0.0,0.0,-8.186036e-02,-6.901297e-02,-9.930481e-02,-1.776357e-15,...,9.020580e-02,-8.554830e-02,-1.684195e-01,-8.653932e-02,-1.387779e-17,-1.360176e-01,0.0,0.0,7.596096e-02,7.570228e-02
75%,0.872258,6.851423e-01,6.898448e-01,1.015677e+00,0.0,0.0,6.380804e-01,6.290786e-01,6.245530e-01,-1.776357e-15,...,7.274632e-01,6.096959e-01,2.389047e-01,6.253823e-01,-1.387779e-17,5.096747e-01,0.0,0.0,7.398906e-01,7.122022e-01
max,1.659204,3.675880e+00,3.981634e+00,2.039375e+00,0.0,0.0,3.697829e+00,4.303846e+00,3.617202e+00,-1.776357e-15,...,2.666353e+00,6.449748e+00,7.861686e+00,3.803699e+00,-1.387779e-17,4.383828e+00,0.0,0.0,3.395609e+00,3.036489e+00

In [ ]:
dfx_transform